domains:
- domain: exokomodo.com
  type: PRIMARY
  zone: exokomodo.com
name: exokomodo
region: sfo
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: ExoKomodo/ExoKomodo
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: exokomodo
  routes:
  - path: /
  source_dir: /