domains:
- domain: services.exokomodo.com
  type: PRIMARY
name: exokomodo
region: sfo
services:
- dockerfile_path: do.Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: ExoKomodo/ExoKomodo
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: exokomodo
  routes:
  - path: /
  source_dir: /
